#!/usr/bin/env bash
# download_data.sh — Instructions to obtain ASVspoof 2019 LA dataset
# This script does NOT auto-download (requires institutional registration).
# Follow the steps below manually.

echo ""
echo "============================================================"
echo "  ASVspoof 2019 LA Dataset — Download Instructions"
echo "============================================================"
echo ""
echo "1. Go to: https://datashare.ed.ac.uk/handle/10283/3336"
echo ""
echo "2. Register / log in (free, requires email verification)."
echo ""
echo "3. Download the following files:"
echo "   - ASVspoof2019_LA_train.zip"
echo "   - ASVspoof2019_LA_dev.zip"
echo "   - ASVspoof2019_LA_eval.zip"
echo "   - ASVspoof2019_LA_cm_protocols.zip"
echo ""
echo "4. Extract each zip into: data/raw/ASVspoof2019_LA/"
echo ""
echo "   Expected final structure:"
echo "   data/raw/ASVspoof2019_LA/"
echo "   ├── ASVspoof2019_LA_cm_protocols/"
echo "   │   ├── ASVspoof2019.LA.cm.train.trn.txt"
echo "   │   ├── ASVspoof2019.LA.cm.dev.trl.txt"
echo "   │   └── ASVspoof2019.LA.cm.eval.trl.txt"
echo "   ├── ASVspoof2019_LA_train/flac/   (~25,380 .flac files)"
echo "   ├── ASVspoof2019_LA_dev/flac/     (~24,986 .flac files)"
echo "   └── ASVspoof2019_LA_eval/flac/    (~71,933 .flac files)"
echo ""
echo "5. (Optional) ASVspoof 2021 DF — Phase 4 cross-domain test:"
echo "   Download from: https://zenodo.org/record/4835108"
echo "   Extract to:    data/raw/ASVspoof2021_DF/"
echo ""
echo "============================================================"
